const KEY='coffeeFinance.v1';
const starter={days:[],fixed:[{id:'rent',name:'Аренда',amount:0,category:'Помещение'},{id:'salary',name:'Зарплаты',amount:0,category:'Команда'},{id:'utilities',name:'Коммунальные услуги',amount:0,category:'Помещение'}]};
let state=load();
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Math.round(n||0))+' ₽', pct=n=>(Number.isFinite(n)?n:0).toFixed(1).replace('.',',')+'%';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(starter)}catch{return structuredClone(starter)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function range(){const now=new Date(),v=$('#periodSelect').value;let from=new Date(0),to=new Date(8640000000000000);if(v==='month')from=new Date(now.getFullYear(),now.getMonth(),1);if(v==='prev'){from=new Date(now.getFullYear(),now.getMonth()-1,1);to=new Date(now.getFullYear(),now.getMonth(),0,23,59,59)}if(v==='quarter')from=new Date(now.getFullYear(),now.getMonth()-2,1);if(v==='year')from=new Date(now.getFullYear(),0,1);return state.days.filter(d=>{let x=new Date(d.date+'T12:00:00');return x>=from&&x<=to})}
function totals(days=range()){const revenue=days.reduce((s,d)=>s+d.revenue,0),variable=days.reduce((s,d)=>s+d.ingredients+d.packaging+d.fees+d.other,0),orders=days.reduce((s,d)=>s+d.orders,0),fixed=state.fixed.reduce((s,x)=>s+x.amount,0),months=$('#periodSelect').value==='year'?12:$('#periodSelect').value==='quarter'?3:$('#periodSelect').value==='all'?Math.max(1,new Set(days.map(d=>d.date.slice(0,7))).size):1,fixedApplied=fixed*months,gross=revenue-variable,profit=gross-fixedApplied;return{revenue,variable,orders,fixed,fixedApplied,gross,profit,margin:revenue?profit/revenue*100:0,grossMargin:revenue?gross/revenue*100:0,avg:orders?revenue/orders:0,roi:(variable+fixedApplied)?profit/(variable+fixedApplied)*100:0,breakEven:revenue?fixedApplied/(gross/revenue):0}}
function render(){const d=range(),t=totals(d);$('#kpis').innerHTML=[['↗','Выручка',money(t.revenue),`${d.length} рабочих дней`],['◇','Чистая прибыль',money(t.profit),pct(t.margin)+' от выручки'],['◎','Средний чек',money(t.avg),`${t.orders} чеков`],['⌁','Точка безубыточности',money(t.breakEven),'необходимая выручка']].map((x,i)=>`<article class="kpi"><div class="kpi-icon">${x[0]}</div><div class="kpi-label">${x[1]}</div><div class="kpi-value ${i===1?(t.profit>=0?'positive':'negative'):''}">${x[2]}</div><div class="kpi-note">${x[3]}</div></article>`).join('');renderChart(d);renderRatios(t);renderDays(d);renderFixed();renderInsights(t,d)}
function renderChart(days){const el=$('#chart');if(!days.length){el.innerHTML='<div class="chart-empty">Добавьте данные, чтобы увидеть динамику</div>';return}let points=[...days].sort((a,b)=>a.date.localeCompare(b.date)).slice(-20),max=Math.max(...points.flatMap(d=>[d.revenue,d.ingredients+d.packaging+d.fees+d.other]),1);el.innerHTML=points.map(d=>`<div class="bar-group" title="${d.date}: ${money(d.revenue)}"><i class="bar income" style="height:${d.revenue/max*90}%"></i><i class="bar expense" style="height:${(d.ingredients+d.packaging+d.fees+d.other)/max*90}%"></i><small>${d.date.slice(8)}</small></div>`).join('')}
function renderRatios(t){let arr=[['Валовая маржа',t.grossMargin,60,'Выручка за вычетом переменных затрат'],['Рентабельность продаж',t.margin,20,'Чистая прибыль на каждый рубль выручки'],['ROI расходов',t.roi,30,'Отдача на все вложенные средства'],['Доля переменных затрат',t.revenue?t.variable/t.revenue*100:0,35,'Сырьё, упаковка, комиссии и прочее']];$('#ratios').innerHTML=arr.map(x=>`<div class="ratio"><div class="ratio-top"><span>${x[0]}</span><strong class="${x[1]>=x[2]?'positive':''}">${pct(x[1])}</strong></div><div class="progress"><i style="width:${Math.max(0,Math.min(100,x[1]))}%"></i></div><p>${x[2]?'Ориентир: '+x[2]+'%. ':''}${x[3]}</p></div>`).join('')}
function renderDays(days){let rows=[...days].sort((a,b)=>b.date.localeCompare(a.date));$('#daysEmpty').style.display=rows.length?'none':'block';$('#daysTable').innerHTML=rows.map(d=>{let v=d.ingredients+d.packaging+d.fees+d.other,p=d.revenue-v;return`<tr><td>${new Date(d.date+'T12:00').toLocaleDateString('ru-RU',{day:'2-digit',month:'short'})}</td><td><strong>${money(d.revenue)}</strong></td><td>${money(v)}</td><td>${d.orders}</td><td class="${p>=0?'positive':'negative'}">${money(p)}</td><td><button class="delete" data-day="${d.id}" title="Удалить">×</button></td></tr>`}).join('')}
function renderFixed(){$('#fixedList').innerHTML=state.fixed.map(x=>`<div class="expense-item"><span class="expense-icon">${x.category==='Команда'?'♙':'⌂'}</span><div><p>${esc(x.name)}</p><small>${esc(x.category)}</small></div><strong>${money(x.amount)}</strong><button class="delete" data-fixed="${x.id}">×</button></div>`).join('');$('#fixedTotal').textContent=money(state.fixed.reduce((s,x)=>s+x.amount,0))}
function renderInsights(t,days){let daily=days.length?t.revenue/days.length:0,needed=Math.max(0,t.breakEven-t.revenue),best=days.length?[...days].sort((a,b)=>b.revenue-a.revenue)[0]:null;$('#insights').innerHTML=[['☕','Средняя выручка в день',money(daily)+' — ваш текущий темп.'],['◉','Запас прочности',t.revenue?`${pct((t.revenue-t.breakEven)/t.revenue*100)} до точки безубыточности.`:'Появится после внесения выручки.'],['↗','Лучший день',best?`${new Date(best.date+'T12:00').toLocaleDateString('ru-RU')} — ${money(best.revenue)}.`:'Пока недостаточно данных.'],['◎','До безубыточности',needed?`Нужно заработать ещё ${money(needed)}.`:'Расходы покрыты — бизнес в плюсе.']].map(x=>`<div class="insight"><span>${x[0]}</span><strong>${x[1]}</strong><p>${x[2]}</p></div>`).join('')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.addEventListener('click',e=>{let open=e.target.closest('[data-open]');if(open){let dlg=$('#'+open.dataset.open);if(open.dataset.open==='dayModal')dlg.querySelector('[name=date]').value=new Date().toISOString().slice(0,10);dlg.showModal()}let day=e.target.dataset.day;if(day&&confirm('Удалить запись за день?')){state.days=state.days.filter(x=>x.id!==day);save()}let fixed=e.target.dataset.fixed;if(fixed&&confirm('Удалить постоянный расход?')){state.fixed=state.fixed.filter(x=>x.id!==fixed);save()}});
$('#dayForm').addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target),num=k=>Number(f.get(k))||0;state.days.push({id:crypto.randomUUID(),date:f.get('date'),revenue:num('revenue'),orders:num('orders'),ingredients:num('ingredients'),packaging:num('packaging'),fees:num('fees'),other:num('other'),note:f.get('note')});save();e.target.closest('dialog').close();e.target.reset();toast('Рабочий день сохранён')});
$('#fixedForm').addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target);state.fixed.push({id:crypto.randomUUID(),name:f.get('name'),amount:Number(f.get('amount'))||0,category:f.get('category')});save();e.target.closest('dialog').close();e.target.reset();toast('Расход добавлен')});
$('#periodSelect').addEventListener('change',render);
$('#exportBtn').addEventListener('click',()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`coffee-finance-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Резервная копия создана')});
$('#importFile').addEventListener('change',async e=>{try{let data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.days)||!Array.isArray(data.fixed))throw Error();state=data;save();toast('Данные восстановлены')}catch{alert('Не удалось прочитать файл. Выберите корректный JSON-экспорт.')}e.target.value=''});
function toast(s){let el=$('#toast');el.textContent=s;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
render();
